<?php
function hello_user_menu() {
    $items = array();
    $items['new_user'] = array(
        'title' => 'Welcome!',
        'page callback' => 'welcome',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function hello_user_user_insert() {
    $_GET['destination'] = 'new_user';
}

function welcome() {
    return '<p>You have created a new account. Congratulations!</p>';
}
